### ISSUE TITLE
setRepeat not working

### ISSUE THREAD

**Issue by userbq201** [twolfson/gif-encoder#14]
set `gif.setRepeat(-1)` but infinity. All code [lint from gist code](https://gist.github.com/userbq201/32b78fd38b6385938d8a9f769afc13a0)

**Comment by twolfson** [comment]
It's been a while since I've maintained this but according to the documentation setting it to `-1` will cause it to repeat once whereas `0` will make it repeat infinite times:

https://github.com/twolfson/gif-encoder/tree/0.6.1#setrepeatn
