### ISSUE TITLE
question regarding the palette

### ISSUE THREAD

**Issue by arnaudambro** [twolfson/gif-encoder#18]
Hi again,
I am new to image treatment, so maybe you'll find my question stupid, and maybe you won't want to spend time answering me, I'd totally understand.

As far as I understand, we can use a palette and indexed pixels to this palette instead of a brut array of pixels. I don't know exactly the reason, but I guess it is supposed to reduce the size of the final GIF file (is it ?).

So my question is the following : in your `README`, you mention this :

> palette `Array` - Array of pixels to use as palette for the frame. It should follow the sequence of `r`, `g`, `b`, `a` **and be `4 * height * width` in length.**

I don't understand this sentence "[...] and be `4 * height * width` in length." : if the palette is supposed to have a set of colors to distribute to the pixel indexed frame, why should it have the same length of the (non-pixel-indexed) frame ? 

![no-transparent-dispose-3](https://user-images.githubusercontent.com/31724752/47926666-663b0b00-dec1-11e8-990f-eb302d095c5b.gif)

In the gif above, for example, there are four colors, so I assume the palette would only be `[34,41,173,1,163,206,73,1,197,1,27,1,0,0,0,1 ]`, wouldn't it ?

**Comment by twolfson** [comment]
Ah, you're correct. The latter `4 * height * width` was added accidentally. I believe I rushed through on the documentation there. I'll update it ASAP. Good catch!

**Comment by arnaudambro** [comment]
Good, it makes more sense to me now ! Thanks !
