### ISSUE TITLE
Broken gifs with jimp images?

### ISSUE THREAD

**Issue by myusf01** [twolfson/gif-encoder#20]
When I'm taking some screenshots with puppeteer and encode them  the result is okay but if I would like to edit these shots with JIMP then encode things goes messy and results are only broken gifs.

**Comment by twolfson** [comment]
It sounds like there's an issue with reading your source data in as an RGBA array. `gif-encoder` only really works with that so it's agnostic to JIMP or a `.png` file - as long as how you load it creates an RGBA array:

https://github.com/twolfson/gif-encoder/tree/0.7.2#addframeimagedata-options
