### ISSUE TITLE
Weird gif

### ISSUE THREAD

**Issue by 19hours** [twolfson/gif-encoder#22]
Thanks for building this lib, I am facing some problems generating a gif. Is it my data that is corrupted?

```
sharp(jpeg)
      .raw()
      .toBuffer({ resolveWithObject: true })
      .then((value) => {
        const pixels = new Uint8ClampedArray(value.data.buffer);
        console.log(pixels);
        var gif = new GifEncoder(600, 900);
        var file = require("fs").createWriteStream("img.gif");
        gif.pipe(file);
        gif.writeHeader();
        gif.addFrame(pixels);
        gif.finish();
      });
```

The end result is this 1 frame gif:
<img width="388" alt="Screenshot 2022-08-06 at 11 34 50 AM" src="https://user-images.githubusercontent.com/22576219/183232041-9bd8cc84-2a1f-49ea-a4ad-35f544248c5f.png">

**Comment by 19hours** [comment]
When I check the jpeg file it is a valid jpeg image

**Comment by twolfson** [comment]
The code looks reasonable to me. I have a few things I'd sanity check on:

- Are the dimensions correct?
- Is the `pixels` data in RGB or RGBA? (`gif-encoder` expects RGBA, https://github.com/twolfson/gif-encoder)
    - Bonus sanity check here: `pixels.length` should equal `width * height * 4` (width * height * RGBA)

Hope that helps =)

**Comment by 19hours** [comment]
Dimensions was the problem, thanks ~
