### ISSUE TITLE
Is the correct value UNLICENSED for the licenses field in package.json?

### ISSUE THREAD

**Issue by kuroppe1819** [twolfson/gif-encoder#24]
I noticed the licenses field in package.json is MIT. Is the correct value UNLICENSED ?
https://github.com/twolfson/gif-encoder/blob/master/package.json#L20-L21

**Comment by twolfson** [comment]
The license is kind of sticky due to forking from `gif.js`, which was using MIT. The full explanation is in the README:

https://github.com/twolfson/gif-encoder#unlicense

That's a good point though -- maybe we should state both in the `package.json`? Unsure how confusing that'd be or not =/
