### ISSUE TITLE
Add image frame to gif

### ISSUE THREAD

**Issue by Wodki** [twolfson/gif-encoder#9]
var file = require('fs').createWriteStream('img.gif');
    gif.pipe(file);
    gif.writeHeader();    

    fs.createReadStream('mygif.gif')
    .pipe(new GIFDecoder)
    .pipe(concat(function(frames) {
        console.log(frames)
        for (var i=0; i<frames.length; i++) {
            gif.addFrame(frames[i]);
        }
        gif.finish();
    }));

so I am trying to add a single frame to the gif, that is my image/other gif/whatever but I cant at best I get a black gif, any ideas? I have been trying to do so for the past 2-3 days with this and other modules but with no success, any help will be really appreciated, thanks.

ps: I also tried converting a png to base64 but as I came to understand it doesnt accept base 64.

**Comment by twolfson** [comment]
I'm going to guess you're using `gif-stream` for `GIFDecoder`:

https://www.npmjs.com/package/gif-stream

This package returns an array of RGB pixels whereas we expect RGBA. As a result, we are likely reading the second frame's red channel as our alpha channel.

I suggest attacking this in 2 parts:

- Get a script running locally with known RGBA data
    - Copy our `checkerboard-pixels.json` and verify it looks good
        - https://github.com/twolfson/gif-encoder/blob/0.6.0/test/test-files/checkerboard-pixels.json
    - Example usage: https://github.com/twolfson/gif-encoder/blob/0.6.0/test/gif-encoder_test.js#L9-L26
- Adjust `gif-stream` data to include alpha channel or move to a library that loads GIF frames with an alpha channel (e.g. `get-pixels`)
    - https://github.com/scijs/get-pixels

**Comment by Wodki** [comment]
Thanks for the guidance!
Adding the RGBA from your json by simply doing `gif.addFrame(json_array);` worked fine, as well as doing the same for other 10x10 images, by unfortunately it didn't for bigger images like 200x200 or bigger. It does display the data in the gif, but its messed up its not the image, (yep I passed RGBA not RGB)
